config/routes.rb
Feed::Application.routes.draw do
  resources :mygames

  root :to => 'feeds#index'
  resources :feeds

  resources :games do
    member do
      get :icon
    end
    collection do
      get :search
    end
  end

  match '/fb_channel', :controller => 'misc', :action => 'fb_channel'
  match '/bookmark', :controller => 'misc', :action => 'canvas'
  match '/message/:action', :controller => 'misc'

end

app/models/facebook_app.rb
class FacebookApp
  def self.access_token
    Rails.cache.fetch('app_access_token', :expires_in=>1.day) do
      self.any_app_access_token(FBConf.app_id, FBConf.secret_key)
    end
  end
  
  def self.any_app_access_token(app_id, secret_key)
    oauth = Koala::Facebook::OAuth.new(app_id, secret_key)
    oauth.get_app_access_token
  end
end

app/models/fb_conf.rb
require 'ostruct'
config = (YAML.load_file(Rails.root.to_s + '/config/fbconf.yml')[Rails.env] rescue {}).merge(ENV)
FBConf = OpenStruct.new(config)

app/models/game.rb
class Game < ActiveRecord::Base
  has_many :mygames, :dependent=>:destroy

  def self.get_by_app_id(app_id, access_token=nil)
    game = self.find_by_app_id(app_id)
    return game if game
    game = Game.new(:app_id=>app_id)
    if game.update_fb_info
      game
    else
      nil
    end
  end
  
  def self.search(query)
    game = Game.find_by_name(query)
    if game
      [game]
    else
      Game.find :all, :conditions=>['UPPER(name) like ?', "%#{query.upcase}%"],
        :order=>'weekly_active_users desc', :limit=>30
    end
  end
    
  def update_fb_info
    graph = Koala::Facebook::API.new
    result = graph.api("/#{app_id}")
    return false unless result
    raise "no logo_url" if result['logo_url'].blank?
    result.delete('id')
    result = result.delete_if {|k,v| !self.attributes.keys.include?(k)}
    self.update_attributes(result)
    true
  end
  
  def for_client
    {:appid=>app_id, :name=>name, :icon_url=>icon_url}
  end
end

app/models/mygame.rb
class Mygame < ActiveRecord::Base
  belongs_to :game
  belongs_to :user
  validates_presence_of :game, :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :mygames
  has_many :games, :through=>:mygames
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

protected
  def fb_user
    return @user if @user
    oauth = koala_oauth
    user_info = oauth.get_user_info_from_cookies(cookies)
    user_id = nil
    if user_info
      @fb_token = user_info['access_token']
      user_id = user_info['user_id']
    elsif params[:signed_request]
      user_info = oauth.parse_signed_request params[:signed_request]
      @fb_token = user_info['oauth_token']
      user_id = user_info['user_id']
    elsif params[:code]
      @fb_token = oauth.get_access_token(params[:code])
      graph = Koala::Facebook::GraphAPI.new(@fb_token)
      user_info = graph.api('/me')
      @user = User.find_or_create_by_facebook_uid(user_info['id'])
    end
    @user = User.find_or_create_by_facebook_uid(user_id) if user_id
  rescue Exception=>e
    # raise e
    @user = @fb_token = nil
  end

  def require_fb_user
    unless fb_user
      redirect_to_oauth
    end
  end

  def koala_oauth
    redirect_url = "http://apps.facebook.com/#{FBConf.canvas_name}"
    Koala::Facebook::OAuth.new(FBConf.app_id, FBConf.secret_key, redirect_url)
  end
  
  def redirect_to_oauth
    redirect_url = "http://apps.facebook.com/#{FBConf.canvas_name}"
    
    @oauth_url = "https://www.facebook.com/dialog/oauth/?client_id=#{FBConf.app_id}&redirect_uri=#{CGI.escape(redirect_url)}&scope=read_stream"
    render :layout=>'oauth'
  end
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  skip_before_filter :verify_authenticity_token
  before_filter :require_fb_user
  
  def index
    @games = fb_user.games.map {|g| g.app_id}
  end
  
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def icon
    g = Game.get_by_app_id(params[:id])
    redirect_to g.icon_url
  rescue Exception=>e
    render(:file=>"#{Rails.root}/public/404.html", :status=>404)
  end
  
  def search
    games = params[:query].blank? ? [] : Game.search(params[:query])
    render :json=>games.collect(&:for_client)
  end
end

app/controllers/misc_controller.rb
class MiscController < ApplicationController
  
  def fb_channel
    response.headers['Pragma'] = 'public'
    expires_in 1.year, :public=>true
    response.headers["Expires"] = CGI.rfc1123_date(Time.now + 1.year)
    render :text=>'<script src="//connect.facebook.net/en_US/all.js"></script>' + "\n"
  end
  
  def canvas
    redirect_to "http://apps.facebook.com/#{FBConf.canvas_name}"
  end
end

app/controllers/mygames_controller.rb
class MygamesController < ApplicationController
  before_filter :require_fb_user
  # GET /mygames
  # GET /mygames.json
  def index
    @mygames = Mygame.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @mygames }
    end
  end

  # GET /mygames/1
  # GET /mygames/1.json
  def show
    @mygame = Mygame.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @mygame }
    end
  end

  # GET /mygames/new
  # GET /mygames/new.json
  def new
    @mygame = Mygame.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @mygame }
    end
  end

  # GET /mygames/1/edit
  def edit
    @mygame = Mygame.find(params[:id])
  end

  # POST /mygames
  # POST /mygames.json
  def create
    appids = params[:appids].split(',')
    games = appids.collect {|appid| Game.get_by_app_id(appid.to_s, @fb_token)}.compact
    fb_user.games = games
    render :text=>'success'
  end

  # PUT /mygames/1
  # PUT /mygames/1.json
  def update
    @mygame = Mygame.find(params[:id])

    respond_to do |format|
      if @mygame.update_attributes(params[:mygame])
        format.html { redirect_to @mygame, notice: 'Mygame was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @mygame.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mygames/1
  # DELETE /mygames/1.json
  def destroy
    @mygame = Mygame.find(params[:id])
    @mygame.destroy

    respond_to do |format|
      format.html { redirect_to mygames_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mygames_helper.rb
module MygamesHelper
end

app/views/feeds/index.html.erb
<script type="text/x-handlebars" data-template-name="game-selector">
{{#with game}}
  <li>
    <a class="gu_button blue" title="add game" {{action "add"}}><img src="{{unbound icon_url }}" /> {{name}}</a>
  </li>
{{/with}}
</script>

<script type="text/x-handlebars" data-template-name="select-games">
    <div id="overlay"></div>
    <div class="generic_dialog">
      <div class="generic_dialog_popup">
        <div id="pop_content" class="pop_content sp">
          <div class="for_mobile"><a href="javascript:void(0)" class="gu_button" {{action "close"}}>Back</a></div>
          <h2>
            <div class="close for_pc"><a href="javascript:void(0)" {{action "close"}}>X</a></div>
            Select the games you play to see the feeds
          </h2>
          <div class="no_games_msg"><p>We cannnot detect any game on your homepage or your feeds :( </p></div>
          <div class="gray">
            <p>Here are games you have selected</p>
            <ul class="game_names clearfix">
              {{#each App.gamesController.currentGames}}
                <li class="game_name">
                  {{view Em.Checkbox checkedBinding="selected"}}
                  <img src="{{unbound icon_url }}" />
                  {{name}}
                </li>
              {{/each}}
            </ul>
          </div>
          <div class="show_games_msg">
            <div class="gray">
              <p>Here are the games you and your friends recently played</p>
              <ul id="games_list" class="game_names_btn clearfix">
                {{#each App.gamesController.content }}
                  {{view App.GameSelectorView gameBinding="this"}}
                {{/each}}
                <li class="game_name">
                  <a href="javascript:void(0)" class="suggest" id="suggest_more" {{action "suggestMore"}}>Suggest more...</a>
                </li>
              </ul>
            </div>
            <div class="gray">
              <p>Search for games to add</p>
              <p>
                {{view Em.TextField class="search" valueBinding="App.gamesController.query"}}
                <input type="button" class="gu_button green" value="Search" {{action "search"}}/>
              </p>
              <ul id="search_list" class="game_names_btn clearfix">
                {{#each App.gamesController.searchResults}}
                  {{view App.GameSelectorView gameBinding="this"}}
                {{/each}}
              </ul>
            </div>
          </div>
          <div class="dialog_buttons"><input type="button" {{action "save"}} value="Save"/></div>
        </div>
      </div>
    </div>
</script>


<script type='text/x-handlebars' data-template-name='post'>
{{#with content}}
  <div {{bindAttr class="row collapsed"}}>
    <div class="dont_click"><a href="javascript:void(0)" {{action "removeMe"}}>Do not collect with 1-click bonuses</a></div>
    <a href="http://www.facebook.com/profile.php?id={{unbound actor_id}}" class="fb_pic">
      <img src="http://graph.facebook.com/{{unbound actor_id}}/picture?type=square" />
    </a>
    <div class = "mainWrapper">
      <h6 class="fb_name"><a href="javascript:void(0)" {{action "viewActor"}}><fb:name uid="{{unbound actor_id}}" useyou="false" linked="false"></fb:name></a></h6>
      <div class="avatar"><img src="{{unbound picSrc}}" /></div>
      <div class="comment_text">
{{#if message }}
        <h6 class="uiStreamMessage"><span class="messageBody">{{ message }}</span></h6>
{{/if}}
        <div class="uiAttachmentTitle">
          <a target="_blank" href="{{unbound postLink}}">{{title}}</a>
        </div>
        <p class="feed_txt">{{ attachment.caption }}</p>
        <p class="feed_txt">{{ attachment.description }}</p>
        <img class="icon_img left" src="{{unbound game_icon}}" width=16 height=16>
        <div {{bindAttr class="like_this:like_this liked"}}>
          
          <span class="like"><a href="javascript:void(0)" {{action "likeMe"}} class="l_txt">Like</a></span>
          <span class="unlike">Liked</span>
          
        </div>
        <div {{bindAttr class="no_likes"}}>
          <table cellspacing="0" cellpadding="0" class="l_bbl left"><tbody><tr>
            <td><div class="button_nub"><s></s><i></i></div></td>
            <td><div class="button_count">{{ like_count }}</div></td></tr></tbody>
          </table> 
        </div>
        <div class="itm">&middot;
          <abbr class="timestamp uiStreamSource"><a target="_blank" href="{{unbound permalink}}">{{ relative_time }}</a></abbr>
{{#if actionText }}
          <span class="UIActionLinks"> · <a target="_blank" href="{{unbound postLink}}">{{actionText}}</a></span>
{{/if}}
        </div>
      </div>
    </div>
    <div class="clicked">
      <div class="uiAttachmentTitle">
        <a target="_blank" href="{{unbound permalink}}">{{title}}</a>
      </div>
    </div>
  </div>
{{/with}}
</script>

<script type='text/x-handlebars' data-template-name='no-posts'>
  <p>Sorry, no feeds are found. Check back later.</p>
</script>

<div class="content">
  <h1 class="for_mobile">My Game Feeds</h1>
  
  <div class="sidecol">
    <div class="for_pc">
      <h4><div class="edit"><a href="javascript:void(0)" onclick="App.showGameSelector()">edit</a></div> My Games</h4>
      <script type="text/x-handlebars">
      <ul class="sidenav"> 
      {{#each App.selectedGames }}
      {{#view App.GameFilterView contentBinding="this"}}
      {{#with content}}
        <a href="javascript:void(0)">
      {{#if icon_url }}
          <img {{bindAttr src="icon_url"}} class="icon_img" {{bindAttr alt="name"}}> {{name}}
      {{else}}
          {{name}}
      {{/if}}
        </a>
      {{/with}}
      {{/view}}
      {{/each }}
      </ul>
      <div class="tellme">
      </div>
      </script>
    </div>
    <div class="for_mobile">
      <h4><div class="edit"><a href="javascript:void(0)" onclick="App.showGameSelector()">edit</a></div> My Games</h4>
      <form action="../">
      <select>
          <option>Farmville</option>
          <option>CastleVille</option>
          <option>Pioneer Trail</option>
          <option>Sims Social</option>
          <option>Monster World</option>
          <option>Empires and Allies</option>
      </select>
      </form>
    </div>
    <ul class="links">
      <li><a href="http://gamersunite.coolchaser.com/topics/95930" target="_blank">Feedback/Suggestions</a></li>
      <li><a href="http://gamersunite.coolchaser.com/topics/95931" target="_blank">Report a Bug</a></li>
    </ul>
  </div>
  <div class="maincol">
    <div class="title_widget">
      <h1 class="for_pc">My Game Feeds</h1>
      <div class="options">
        <script type="text/x-handlebars">
        {{#view App.FriendOrMeView}}
            <fieldset>
              <input type="radio" class="radio" value="my_friends_post" name="feed_options" {{action "isFriend" on="change"}} checked>
              <label>All Posts</label>
              <input type="radio"  value="my_posts" class="radio" name="feed_options" {{action "isMe" on="change"}}>
              <label>My Posts</label>
            </fieldset>
        {{/view}}
        </script>
      </div>
      <script type="text/x-handlebars">
      {{#view App.AutoRefreshView id="refresh"}}
        <div class="on_msg">Too heavy? <a href="javascript:void(0)" {{action "turnOff"}}>Stop Auto-Refresh</a></div>
        <div class="off_msg"><a href="javascript:void(0)" {{action "turnOn"}}>Resume Auto-Refresh</a></div>
        <div class="halt_msg">Auto-Refresh paused during 1-Click Bonus</div>
      {{/view}}
      </script>
    </div>
    <h3 class="sub make_pos">
      <script type="text/x-handlebars">
      {{#view App.OneClickView }}
      <div class="tellme for_pc">(<a href="javascript:$('#whats_1bonuses').toggle(); void(0);" class="tell_me_more">What's this?</a>)</div>
      <div class="one_click_bonus default">
        <div class="desc">Collect bonuses, each in</div>
        <select class="gu_time" id="gu_time">
          <option value="5">5 secs</option>
          <option selected="" value="10">10 secs</option>
          <option value="15">15 secs</option>
          <option value="20">20 secs</option>
          <option value="25">25 secs</option>
          <option value="30">30 secs</option>
          <option value="45">45 secs</option>
          <option value="60">60 secs</option>
        </select>
        <div class="comment_opt">
          {{#view Em.Checkbox checkedBinding="App.oneClickController.leaveComment"}}
            Leave comments on 10% of the posts
          {{/view}}
        </div>
        <a {{action "start"}}  href="#" class="gu_button">Collect!</a>
      </div>
      <div class="one_click_bonus running">
        <span class="processing">Collecting bonuses now (please do not close popup window) <%= image_tag("ajax-loader.gif") %></span>
        <span class="halt">Paused collecting bonuses (click resume to restart) </span>
        <a {{action "pause"}} href="#" class="gu_button yellow pause">Pause</a>
        <a {{action "resume"}} href="#" class="gu_button green resume">Resume</a>
        <a {{action "stop"}} href="#" class="gu_button red stop">Stop</a>
      </div>
      <div class="auto_comment_div">
        <div class="chat-bubble">
          <p class="close">
            <a {{action "closeCommentBox"}} alt="close"><%= image_tag("close.gif", :alt=>"close") %></a>
          </p>
          <div class="auto_comment">
            <p><strong>Let your friends know you helped with their requests!</strong></p>
            {{#view Em.TextArea valueBinding="App.oneClickController.comment" }}
            {{/view}}
          </div>
          <div class="chat-bubble-arrow-border border_left"></div>
          <div class="chat-bubble-arrow arrow_left"></div>
        </div>
      </div>
    {{/view}}
    </script>
    </h3>
    <div style="display:none;" id="whats_1bonuses">
      <div class="what_is">
        <p>Grab bonuses at once with 1-Click!</p>
          <ul class="arrow">
            <li>It'll open a pop-up window to click the bonuses so please allow popups.</li>
            <li>Please don't close the popup window until it's done; the window will close automatically at the end.</li>
            <li>Some games take longer to load to get the bonuses, so adjust the time to grab each bonuses into longer seconds.</li>
            <li>Hover over the posts and select "Don't collect this for 1-click bonuses" if you don't want to click on that bonus</li>
            <li>Leave comments on 5% of the posts so your friends know you helped them (you don't want to be too spammy!)</li>
          </ul>
      </div>
    </div>
    <div class="ad">
      <div id='div-gpt-ad-1346565107896-0' style='width:728px; height:90px;'>
      <script type='text/javascript'>
      googletag.cmd.push(function() {
      googletag.display('div-gpt-ad-1346565107896-0'); });
      </script>
      </div>
    </div>
    <div class="fetching"></div>
    <div class="row_wrap" id="feed">
    </div>
  </div>
</div>
<script>
App.appInit(<%= raw @games %>);
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Game Feeds</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <script type="text/javascript">

    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-173832-21']);
    _gaq.push(['_trackPageview']);

    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();

  </script>
  <script type='text/javascript'>
  var googletag = googletag || {};
  googletag.cmd = googletag.cmd || [];
  (function() {
  var gads = document.createElement('script');
  gads.async = true;
  gads.type = 'text/javascript';
  var useSSL = 'https:' == document.location.protocol;
  gads.src = (useSSL ? 'https:' : 'http:') +
  '//www.googletagservices.com/tag/js/gpt.js';
  var node = document.getElementsByTagName('script')[0];
  node.parentNode.insertBefore(gads, node);
  })();
  </script>

  <script type='text/javascript'>
  googletag.cmd.push(function() {
  googletag.defineSlot('/1005610/Feed_Home_Top_728x90', [728, 90],
  'div-gpt-ad-1346565107896-0').addService(googletag.pubads());
  googletag.pubads().enableSingleRequest();
  googletag.enableServices();
  });
  </script>
</head>
<body>
  <div class="container">
    <%= render :partial=>'/shared/fbmgr' %>
    <%= yield %>
  </div>
</body>
</html>

app/views/layouts/oauth.html.erb
<html>
<body>
  <script>
  window.top.location.href = '<%= raw @oauth_url -%>';
  </script>
</body>
</html>

app/views/mygames/_form.html.erb
<%= form_for(@mygame) do |f| %>
  <% if @mygame.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mygame.errors.count, "error") %> prohibited this mygame from being saved:</h2>

      <ul>
      <% @mygame.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :game_id %><br />
    <%= f.text_field :game_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/mygames/edit.html.erb
<h1>Editing mygame</h1>

<%= render 'form' %>

<%= link_to 'Show', @mygame %> |
<%= link_to 'Back', mygames_path %>

app/views/mygames/index.html.erb
<h1>Listing mygames</h1>

<table>
  <tr>
    <th>Game</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @mygames.each do |mygame| %>
  <tr>
    <td><%= mygame.game_id %></td>
    <td><%= mygame.user_id %></td>
    <td><%= link_to 'Show', mygame %></td>
    <td><%= link_to 'Edit', edit_mygame_path(mygame) %></td>
    <td><%= link_to 'Destroy', mygame, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Mygame', new_mygame_path %>

app/views/mygames/new.html.erb
<h1>New mygame</h1>

<%= render 'form' %>

<%= link_to 'Back', mygames_path %>

app/views/mygames/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Game:</b>
  <%= @mygame.game_id %>
</p>

<p>
  <b>User:</b>
  <%= @mygame.user_id %>
</p>


<%= link_to 'Edit', edit_mygame_path(@mygame) %> |
<%= link_to 'Back', mygames_path %>

app/views/shared/_fbmgr.html.erb
<div id="fb-root"></div>
<script>
  FBMgr.init('<%= FBConf.app_id %>');
</script>